// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (id, created_at, updated_at, name, latitude, longitude)
VALUES ($1, now(), now(), $2, $3, $4)
RETURNING id, created_at, updated_at, name, latitude, longitude
`

type CreateLocationParams struct {
	ID        uuid.UUID
	Name      string
	Latitude  float64
	Longitude float64
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.ID,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getAllLocations = `-- name: GetAllLocations :many
SELECT id, created_at, updated_at, name, latitude, longitude FROM locations
`

func (q *Queries) GetAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, getAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
