// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Location struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Latitude  float64
	Longitude float64
}

type WeatherLog struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Temperature sql.NullString
	WindSpeed   sql.NullString
	CloudCover  sql.NullInt32
	Preassure   sql.NullString
	LocationID  uuid.UUID
}
