// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather_logs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createWeatherLog = `-- name: CreateWeatherLog :one
INSERT INTO weather_logs (id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id)
VALUES (gen_random_uuid(), now(), now(), $1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id, is_debug
`

type CreateWeatherLogParams struct {
	Temperature sql.NullFloat64
	WindSpeed   sql.NullFloat64
	CloudCover  sql.NullInt32
	Preassure   sql.NullFloat64
	LocationID  uuid.UUID
}

func (q *Queries) CreateWeatherLog(ctx context.Context, arg CreateWeatherLogParams) (WeatherLog, error) {
	row := q.db.QueryRowContext(ctx, createWeatherLog,
		arg.Temperature,
		arg.WindSpeed,
		arg.CloudCover,
		arg.Preassure,
		arg.LocationID,
	)
	var i WeatherLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Temperature,
		&i.WindSpeed,
		&i.CloudCover,
		&i.Preassure,
		&i.LocationID,
		&i.IsDebug,
	)
	return i, err
}

const createWeatherLogDebug = `-- name: CreateWeatherLogDebug :one
INSERT INTO weather_logs (id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id, is_debug)
VALUES (gen_random_uuid(), now(), $6, $1, $2, $3, $4, $5, true)
RETURNING id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id, is_debug
`

type CreateWeatherLogDebugParams struct {
	Temperature sql.NullFloat64
	WindSpeed   sql.NullFloat64
	CloudCover  sql.NullInt32
	Preassure   sql.NullFloat64
	LocationID  uuid.UUID
	UpdatedAt   time.Time
}

func (q *Queries) CreateWeatherLogDebug(ctx context.Context, arg CreateWeatherLogDebugParams) (WeatherLog, error) {
	row := q.db.QueryRowContext(ctx, createWeatherLogDebug,
		arg.Temperature,
		arg.WindSpeed,
		arg.CloudCover,
		arg.Preassure,
		arg.LocationID,
		arg.UpdatedAt,
	)
	var i WeatherLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Temperature,
		&i.WindSpeed,
		&i.CloudCover,
		&i.Preassure,
		&i.LocationID,
		&i.IsDebug,
	)
	return i, err
}

const getDailyLogsWithinRange = `-- name: GetDailyLogsWithinRange :many
SELECT AVG(temperature) as temperature, AVG(wind_speed) as speed, AVG(cloud_cover) as cloud_cover, AVG(preassure) as preassure, date_trunc('day', updated_at)::timestamp AS daily_bucket
FROM weather_logs
WHERE location_id = $1::uuid
AND updated_at >= $2::timestamp
AND updated_at <= $3::timestamp
GROUP BY daily_bucket
ORDER BY daily_bucket
`

type GetDailyLogsWithinRangeParams struct {
	ID         uuid.UUID
	RangeStart time.Time
	RangeEnd   time.Time
}

type GetDailyLogsWithinRangeRow struct {
	Temperature float64
	Speed       float64
	CloudCover  float64
	Preassure   float64
	DailyBucket time.Time
}

func (q *Queries) GetDailyLogsWithinRange(ctx context.Context, arg GetDailyLogsWithinRangeParams) ([]GetDailyLogsWithinRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getDailyLogsWithinRange, arg.ID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyLogsWithinRangeRow
	for rows.Next() {
		var i GetDailyLogsWithinRangeRow
		if err := rows.Scan(
			&i.Temperature,
			&i.Speed,
			&i.CloudCover,
			&i.Preassure,
			&i.DailyBucket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHourlyLogsWithinRange = `-- name: GetHourlyLogsWithinRange :many
SELECT AVG(temperature) as temperature, AVG(wind_speed) as speed, AVG(cloud_cover) as cloud_cover, AVG(preassure) as preassure, date_trunc('hour', updated_at)::timestamp AS hourly_bucket
FROM weather_logs
WHERE location_id = $1::uuid
AND updated_at >= $2::timestamp
AND updated_at <= $3::timestamp
GROUP BY hourly_bucket
ORDER BY hourly_bucket
`

type GetHourlyLogsWithinRangeParams struct {
	ID         uuid.UUID
	RangeStart time.Time
	RangeEnd   time.Time
}

type GetHourlyLogsWithinRangeRow struct {
	Temperature  float64
	Speed        float64
	CloudCover   float64
	Preassure    float64
	HourlyBucket time.Time
}

func (q *Queries) GetHourlyLogsWithinRange(ctx context.Context, arg GetHourlyLogsWithinRangeParams) ([]GetHourlyLogsWithinRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getHourlyLogsWithinRange, arg.ID, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHourlyLogsWithinRangeRow
	for rows.Next() {
		var i GetHourlyLogsWithinRangeRow
		if err := rows.Scan(
			&i.Temperature,
			&i.Speed,
			&i.CloudCover,
			&i.Preassure,
			&i.HourlyBucket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeatherLogsByLocation = `-- name: GetWeatherLogsByLocation :many
SELECT id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id, is_debug from weather_logs
where location_id = $1
limit $2
`

type GetWeatherLogsByLocationParams struct {
	LocationID uuid.UUID
	Limit      int32
}

func (q *Queries) GetWeatherLogsByLocation(ctx context.Context, arg GetWeatherLogsByLocationParams) ([]WeatherLog, error) {
	rows, err := q.db.QueryContext(ctx, getWeatherLogsByLocation, arg.LocationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherLog
	for rows.Next() {
		var i WeatherLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Temperature,
			&i.WindSpeed,
			&i.CloudCover,
			&i.Preassure,
			&i.LocationID,
			&i.IsDebug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDebugLogs = `-- name: RemoveDebugLogs :exec
DELETE FROM weather_logs WHERE is_debug = true
`

func (q *Queries) RemoveDebugLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, removeDebugLogs)
	return err
}
