// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather_logs.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createWeatherLog = `-- name: CreateWeatherLog :one
INSERT INTO weather_logs (id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id)
VALUES ($1, now(), now(), $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id
`

type CreateWeatherLogParams struct {
	ID          uuid.UUID
	Temperature sql.NullFloat64
	WindSpeed   sql.NullFloat64
	CloudCover  sql.NullInt32
	Preassure   sql.NullFloat64
	LocationID  uuid.UUID
}

func (q *Queries) CreateWeatherLog(ctx context.Context, arg CreateWeatherLogParams) (WeatherLog, error) {
	row := q.db.QueryRowContext(ctx, createWeatherLog,
		arg.ID,
		arg.Temperature,
		arg.WindSpeed,
		arg.CloudCover,
		arg.Preassure,
		arg.LocationID,
	)
	var i WeatherLog
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Temperature,
		&i.WindSpeed,
		&i.CloudCover,
		&i.Preassure,
		&i.LocationID,
	)
	return i, err
}

const getWeatherLogsByLocation = `-- name: GetWeatherLogsByLocation :many
SELECT id, created_at, updated_at, temperature, wind_speed, cloud_cover, preassure, location_id from weather_logs
where location_id = $1
limit $2
`

type GetWeatherLogsByLocationParams struct {
	LocationID uuid.UUID
	Limit      int32
}

func (q *Queries) GetWeatherLogsByLocation(ctx context.Context, arg GetWeatherLogsByLocationParams) ([]WeatherLog, error) {
	rows, err := q.db.QueryContext(ctx, getWeatherLogsByLocation, arg.LocationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeatherLog
	for rows.Next() {
		var i WeatherLog
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Temperature,
			&i.WindSpeed,
			&i.CloudCover,
			&i.Preassure,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
